### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by wenwenyu** [Kaido0/Unet-BrainTissue-Seg#1]
您好：
我在运行大神的代码时报错，请问你有遇到同样的问题吗，代码地址是[https://github.com/vuhoangminh/Brain-segmentation](url)
错误是运行predict_2d.py时出错，错误信息如下：
_Slice number:  70
Image:  IBSR_10_ana_strip.nii.gz
Traceback (most recent call last):
Number of processed patches:  2
Number of extracted patches:  2
  File "C:/Users/user/Desktop/project/code/Brain-segmentation-master/minh_2d_unet/predict_2d.py", line 254, in <module>
    predict(img_dir_name)
  File "C:/Users/user/Desktop/project/code/Brain-segmentation-master/minh_2d_unet/predict_2d.py", line 216, in predict
    if img_mask_data.item((i, j, iSlice)) == 1:
ValueError: incorrect number of indices for array_
期待大神的回复。

**Comment by Kaido0** [comment]
@WENWENYU 
我没有遇到这个问题，但是根据错误提示，可以先看一看img_mask_data的shape，在unique看一下取值，必要时候可以用matplotlib看一下70层的图，确定一下有没有值是错误的

**Comment by wenwenyu** [comment]
我下载Brain-segmentation工程直接刚开始运行data_handling_2d_patch.py时就报错了，是不是下载的数据集IBSR18 有问题呀，data_handling_2d_patch.py源码中时第54、58、62行处理的数据路径就不对，_hist.nii.gz、_seg.nii.gz、_mask.nii.gz，这三个结尾的文件在下载的IBSR18 中找不到，然后我分别改成IBSR18 数据集中有的_ana_strip.nii.gz、_seg_ana.nii.gz、_ana_brainmask.nii.gz才可以，但训练出来的模型运行predict_2d.py就出现上面的问题的。你方便可以把你运行的代码和数据集分享给我吗。我估计时数据集的问题啊。
非常感谢！

**Comment by wenwenyu** [comment]
IBSR18数据集我是从这网站 https://www.nitrc.org/frs/?group_id=48 下载的。

**Comment by wenwenyu** [comment]
img_mask_data的shape是 (256L, 128L, 256L, 1L)

**Comment by wenwenyu** [comment]
大神，问题解决了。谢谢提醒！
