### ISSUE TITLE
制作train.npy,test.npy,mask.npy

### ISSUE THREAD

**Issue by wenwenyu** [Kaido0/Unet-BrainTissue-Seg#2]
请问你第一步中是如何处理成.npy文件的呢？

**Comment by Kaido0** [comment]
我用的是.mha格式的图像，用SimpleITK工具包直接读取，然后用numpy保存成.npy.在这里1代表图像个数，50代表层数，512为宽和高。
代码可以参考下面这个。不清楚再联系～

`
import SimpleITK as sitk
def read_vol(path,n):
    path=os.path.join(path,n)
    itk_img=sitk.ReadImage(path)
    data=sitk.GetArrayFromImage(itk_img)
    return data

train = np.empty((1, 50, 512, 512))
train_npy=read_vol(path,name)
np.save('train.npy',train_npy)
`

**Comment by Kaido0** [comment]
@WENWENYU 

我用的是.mha格式的图像，用SimpleITK工具包直接读取，然后用numpy保存成.npy.在这里1代表图像个数，50代表层数，512为宽和高。
代码可以参考下面这个。不清楚再联系～

`
import SimpleITK as sitk
def read_vol(path,n):
path=os.path.join(path,n)
itk_img=sitk.ReadImage(path)
data=sitk.GetArrayFromImage(itk_img)
return data

train = np.empty((1, 50, 512, 512))
train_npy=read_vol(path,name)
np.save('train.npy',train_npy)

**Comment by wenwenyu** [comment]
@Kaido0 按照你readme里提到的数据集MICCAI2012，我下载下来的图像格式是.nii.gz格式的，请问你的数据集下载下来的是的吗，还是你转换成.mha格式的呢？

**Comment by wenwenyu** [comment]
我的数据是从这网站下载的：https://my.vanderbilt.edu/masi/workshops/。选择 MICCAI 2012 Grand Challenge and Workshop on Multi-Atlas Labeling 这个的，不知道对不对。
大神。
